name: "repo"
description: "The repo that handles users"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  cloud_firestore: ^5.4.5
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.3
  google_sign_in: ^6.2.2


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true        